### PR TITLE
Don't use _createPane for arbitrary element creation

### PR DESCRIPTION
**Pull request by jfirebaugh**
Best not to use `_` methods -- `_createPane` is gone in Leaflet master. (There's a public `createPane` method but it does something slightly different.)

### CODE REVIEW

**Comment by mourner** [comment]
:+1:

**Comment by jfirebaugh** [comment]
@tristen Anything jogging your memory here? Seems to work fine for me.

**Comment by tristen** [comment]
Just going to test this real quick. If everything seems fine this should be good2go.

**Comment by tristen** [comment]
Yep - this looks great to me!

**Comment by wboykinm** [comment]
With this in mind, what do you recommend I use [in place of `_createPane` here?](https://github.com/wboykinm/reference/blob/master/mapbox.html#L174)

**Comment by jfirebaugh** [comment]
Just inline the definition of [_createPane](https://github.com/Leaflet/Leaflet/blob/6864384d630e46fc5908575befebb19239b1c0d0/src/map/Map.js#L525), so:

```
var topPane = L.DomUtil.create('div', 'leaflet-top-pane', map.getPanes().mapPane);
```

**Pull request merged**
