### PR TITLE
Update geocoding version, remove global version numbering, round coordinates

### PR DESCRIPTION
**Pull request by heyitsgarrett**
We're no longer standardizing `v4` throughout all of our APIs, starting with geocoding, which moves from:

`../v4/geocode/..`

to

`../geocoding/v5/..`

In the interim, I've removed `v4` from the global `config.js` and am leaving it to each API call to include separately.

(I also made the `urlhelper` function name consistent throughout)

cc @tmcw @yhahn

### CODE REVIEW

**Comment by tmcw** [comment]
urlhelper isn't a very good name for what this is. formatURL?

**Comment by tmcw** [comment]
Also, the name of the file and the name of what you call its export should match.

**Comment by heyitsgarrett** [comment]
Y, `urlHelper` was legacy so I didn't rock the boat too much. I've updated everything to `formatUrl` and got tests in order.

@tmcw @jfirebaugh - a final review would be great here before Mergeville, :us:

**Comment by jfirebaugh** [comment]
Convention for multi-word file names is underscore, so it should be `format_url.js` rather than `formatUrl.js`.

**Comment by heyitsgarrett** [comment]
:+1: @jfirebaugh

**Comment by sbma44** [comment]
Added coordinate rounding & associated tests. Good to merge when you're comfortable, @tmcw / @jfirebaugh.

**Pull request merged**
