### PR TITLE
Adds build script to create and publish the bower repo

### PR DESCRIPTION
**Pull request by blackjid**
Hi, we at platanus have been running the `platanus/bower-mapboxjs` repo that is being used by the `mapboxjs` package from bower. Sadly we're not using mapbox to actively so the repo usually gets outdated.

I've build a script that automate the bower building and publishing trying to solve this issues platanus/bower-mapboxjs#2 and #404 and #740

If you are willing to merge the PR you can fork our repo, or if you prefer I can transfer the ownership to you.

Also we can change the endpoint to `mapboxjs` in bower

I hope this is useful for everyone

### CODE REVIEW

**Comment by tmcw** [comment]
Awesome - I will review this next week and scope out merging / running it on an npm publish task

**Comment by blackjid** [comment]
Great, let me know if you need anything.

**Comment by tmcw** [comment]
Okay, took a look:
- This PR creates a `master` branch in which bower releases live. We don't currently have a `master` branch, and I think it would be confusing for `master` to be bower-only. I'd love to use a branch like `bower` that's specific about being bower-specific so that nobody ends up accidentally cloning and developing on `master`.
- The script also creates new git tags of the [same format as we do already](https://github.com/mapbox/mapbox.js/releases) - I know bower is git-tag-dependent, and thus would lead us into the paradox of which branch the git tag should live on. Maybe bower releases could be like `2.0.1-bower`, which is 'pre-release' according to [semver](http://semver.org/), but doesn't sacrifice the existing patterns.

**Comment by tmcw** [comment]
Ah, now I notice, too late, that this is checking out & pushing to a separate repo - got it.

**Comment by tmcw** [comment]
@blackjid thanks, merged & set up at https://github.com/mapbox/mapbox.js-bower - can you [unregister the existing distro so we can adopt it?](http://bower.io/docs/creating-packages/#unregister)

**Comment by blackjid** [comment]
:+1: 

If you want to take over the ownership of [platanus/bower-mapboxjs](https://github.com/platanus/bower-mapboxjs) just let me know. There I have build all mapbox.js tags with this script so bower users can point to any version.

**Comment by tmcw** [comment]
Good call - forked that repo to https://github.com/mapbox/mapbox.js-bower

**Comment by blackjid** [comment]
done. bower `mapboxjs` no longer taken..

**Comment by mrpollo** [comment]
Great work guys thanks, this works great :sob:

ap

**Pull request merged**
