### PR TITLE
[don't merge] Responsive attribution

### PR DESCRIPTION
**Pull request by tristen**
Looks like this _(the gif is a little glitchy)_:

attribution-responsive

cc @jfirebaugh @lxbarth

### CODE REVIEW

**Comment by jfirebaugh** [comment]
This needs to be responsive to the actual size of the map element rather than the window. Like if you have a small map in one corner of the page it should use the (i).

**Comment by tristen** [comment]
@jfirebaugh https://github.com/mapbox/mapbox.js/commit/a1825c49765de666366840715bbf52e5415832d6 look right to you? 

Not sure the best place to document `compact:true` in https://github.com/mapbox/mapbox.js/blob/mb-pages/API.md

**Comment by jfirebaugh** [comment]
> Not sure the best place to document compact:true

Add to the `L.mapbox.map` `options` list:
- `attributionControl`: value can be `{compact: true}` to force a compact attribution icon that shows the full attribution on click, or `{compact: false}` to force the full attribution control. The default is a responsive attribution that collapses when the map is less than 640 pixels wide.

**Comment by jfirebaugh** [comment]
Note that we can make the responsive attribution changes in the next 2.x release, but removing infoControl support will need to wait for 3.0 (which will probably coincide with Leaflet 1.0).

**Comment by lxbarth** [comment]
Can we deprecate the infoControl() API right away?

**Comment by jfirebaugh** [comment]
We could mark it as deprecated in the documentation and `console.log` a warning if it's used. Is that what you had in mind @lxbarth?

**Comment by lxbarth** [comment]
I think that makes sense right? This way we manage expectations that it'll go away in 3.

**Comment by tristen** [comment]
@jfirebaugh @lxbarth 

So just in `map.js` something like this?

``` js
if (this.options.infoControl) {
    console.warn('infoControl has been deprecated in v3.0.0');
}
```

**Comment by tristen** [comment]
-> https://github.com/mapbox/mapbox.js/pull/948

**Pull request closed without merging**
