### PR TITLE
mapbox.js dupe meta descriptions

### PR DESCRIPTION
**Pull request by zachbeattie**
per https://github.com/mapbox/business/issues/2924

### CODE REVIEW

**Comment by zachbeattie** [comment]
@pdgoodman - eyes before I merge? This adds the mapbox.js version # to each meta description that had a duplicate.

**Comment by jfirebaugh** [comment]
These are all generated files; we should update the [generation code](https://github.com/mapbox/mapbox.js/blob/b656f19fd413380b5f88464eccda20b587c85b3b/_docs/generate.js#L30-L31) to include the version number. Otherwise new versions won't get a version number, and these changes will get overwritten if we ever regenerate the files.

**Comment by zachbeattie** [comment]
> we should update the generation code to include the version number. 

Good call @jfirebaugh, although I'm not sure how to make this update. Is this something you can help with?

**Comment by jfirebaugh** [comment]
Sure! Just above and below the lines I linked to you can see examples of how to concatenate the version (in `argv.t`) into other strings. So including it in the description too is a matter of inserting `' + argv.t + '` in the right place in those two lines. You can test that it works by following [these instructions](https://github.com/mapbox/mapbox.js/blob/mb-pages/DOCUMENTING.md#api-documentation) (which in turn assume that you've previously run `npm install`).

**Comment by zachbeattie** [comment]
Awesome, thanks @jfirebaugh. I updated and tested the generation code to include the version number.

**Pull request merged**
