### PR TITLE
Add layouts and posts for plugins.

### PR DESCRIPTION
**Pull request by tmcw**
@tristen @aaronlidman either of you want to adopt this promising young branch?

- [x] Actually build out the CDN scripts and collect the right dist files: https://github.com/mapbox/mapbox.js-plugins/issues/2
- [x] Add links to documentation
- [ ] Visual cleanup?
- [x] Choose and 'curate' this selection of plugins.

### CODE REVIEW

**Comment by tristen** [comment]
Great! I would like to pull this work in my fixed layout branch here https://github.com/mapbox/mapbox.js/tree/fixed-layout. I can take on the visual cleanup.

**Comment by aaronlidman** [comment]
I'll take the build stuff, linking documentation, and curation.

**Comment by tmcw** [comment]
:+1:

**Comment by tristen** [comment]
Closing this as this has been merged into #629

**Pull request closed without merging**
