### PR TITLE
Doc layout quest

### PR DESCRIPTION
**Pull request by tristen**
This commit presents a fixed navigation and header structure to mapbox.js documentation. It also introduces Swiftype to take care of search. One other thing to note is that the landing page is now the first page of the API. Remaining tasks:
- [x] Browser testing
### Splash + API

splash
### Examples

examples
### Plugins

plugins

cc/ @yhahn @lxbarth @tmcw

### CODE REVIEW

**Comment by tmcw** [comment]
Important functional change is search:

2014-02-28 at 3 39 pm

Can we get more space so these tiles don't truncate so quickly, and show search previews?

**Comment by yhahn** [comment]
y thought this as well, @tristen could a wider dropdown (but still compact search area) work ok?

**Comment by tristen** [comment]
I've increased the width and made the only adjustment I found while playing the cross-browser game.

**Comment by yhahn** [comment]
@tristen awesome.

@tmcw want to give this a final review?

**Comment by tmcw** [comment]
:+1: looks great, shipit.

**Pull request merged**
