### PR TITLE
Drop retina conditions and just serve a @2x version

### PR DESCRIPTION
**Pull request by tristen**
Tested and I'm not seeing any disadvantage in doing this. Addresses https://github.com/mapbox/mapbox.js/issues/695 too.

cc @tmcw

### CODE REVIEW

**Comment by tmcw** [comment]
Hmm, I'm not sure that scaling down will really always look exactly the same... thoughts @samanpwbb ?

**Comment by samanpwbb** [comment]
@tmcw scaling down looks exactly the same as long as 2x version is even length/width. Browser rendering fails when the 1/2 size version doesn't fall on the pixel grid. In this case, it should look right.

**Comment by tmcw** [comment]
Cool, then merge it @tristen

**Comment by tmcw** [comment]
This looks like it broke http://localhost:3000/test/manual/standalone.html -

2014-05-27 at 3 52 pm

**Pull request merged**
