### PR TITLE
Fix Leaflet v1 requiring you to offset zooms for yourself

### PR DESCRIPTION
**Pull request by tmcw**
Refs #1178

### CODE REVIEW

**Comment by bsudekum** [comment]
This fails for zoom level 0 which requests tile `-1/0/0`.

**Comment by tmcw** [comment]
Do you know what the previous behavior was?

**Comment by bsudekum** [comment]
@tmcw it'd load tile `0/0/0`, here is an example: http://bl.ocks.org/bsudekum/0b630fab6ce551784a4c91815a9b1b0a

**Comment by bsudekum** [comment]
One idea here is that in leaflet 0.7, tile 0/0/0 was scaled down to 256px. This is not the case anymore in 1.0.

**Comment by tmcw** [comment]
@mourner I'm not seeing a way through this problem in Leaflet v1.0.1, could you take a look? We need the behavior to be:

| Leaflet Zoom | Tile | Tile Size | Pixel Size on Screen |
| --- | --- | --- | --- |
| 0 | 0/0/0 | 512x512px | 256x256px |
| 1 | 0/0/0 | 512x512px | 512x512px |
| 2 | 1/0/0 | 512x512px | 512x512px |

And so on. We were, remarkably, able to make this work with default Leaflet 0.7 behavior, but I'm finding no combination of parameters that will underscale a tile at one specific zoom in this way in Leaflet v1.0.1. Unfortunately this is a breaking issue for Mapbox.js and very high-impact, since styleLayer is the recommended layer and 512px is the natural size.

cc @bsudekum @yhahn since this is part of 5" quest.

**Comment by IvanSanchez** [comment]
I think it might be time to reopen https://github.com/Leaflet/Leaflet/issues/3165. Implementing that would solve this specific behaviour nicely.

**Comment by bb-juliogarcia** [comment]
@IvanSanchez - I've gone ahead and submitted a pull request for the issue at https://github.com/Leaflet/Leaflet/issues/3165. It is unit tested and working for us on our client

**Comment by tmcw** [comment]
Tracking in issue instead of PR: #1192

**Pull request closed without merging**
