### PR TITLE
Docs navigation

### PR DESCRIPTION
**Pull request by tristen**
Revising of the docs header:
- Re-introduce the mapbox masthead on docs pages.
- Spruce the overview page on /api/ by condensing the frontpage into it.
- Play off the green headline for site title.

### CODE REVIEW

**Comment by aaronlidman** [comment]
download

**Comment by tmcw** [comment]
The visual navigation hierarchy is kind of a switchback here:

2014-02-12 at 9 29 am

**Comment by tristen** [comment]
Yeah, I've returned to this tabbed approach after a number of iterations for a couple reasons:
1. The relationship to its page title + TOC is strong
   
2. As @tmcw pointed out to me last week. We have seen a consistent bump in traffic since we introduced the fixed sidebar (we clear the 5k mark consistently on weekdays) I think the relationship the tabs have in the sidebar to its TOC is a good indicator that we are doing something right and its something I don't want to mess with.

untitled

I am not seeing hierarchy as a problem here.

**Comment by tmcw** [comment]
> We have seen a consistent bump in traffic since we introduced the fixed sidebar (we clear the 5k mark consistently on weekdays)

I would put money on: this is mostly because we've restructured API docs as separate pages.

Hierarchy is _the_ problem of IA.

**Comment by lxbarth** [comment]
This is not tight yet. Agreed that there's still an issue w/ hierarchy.

**Comment by tristen** [comment]
Here's a new version that address' the hierarchy concerns.

**[link](https://f.cloud.github.com/assets/61150/2153147/557ce11e-9423-11e3-9df4-ef4d2caa8c10.png)**

Notes: 
- Developer link in the top masthead is set to active
- I've pulled the navigation back out of the sidebar and present them in the same manner as the top masthead navigation. Keeping consistent with this style I think is good.
- Title bar is above the sidebar, larger and above the sidebar.

**Comment by tristen** [comment]
Here's a new revision:

**Comment by tristen** [comment]
Looking at this more, I'm not sure why we would want to pull the site title far off to the left and not connect the relationship between is and the site navigation better. I think a version like this feels better:



I'm not seeing this hurt hierarchy even with the sidebar being to the left.

**Comment by tristen** [comment]
Moving to a different branch!

**Pull request closed without merging**
