### PR TITLE
Remove examples.map IDs from examples

### PR DESCRIPTION
**Pull request by lyzidiamond**
This (super secret project) PR:
- Removes `examples.#####` map IDs from **most** Mapbox.js examples (it had to stay in certain examples, which will be ticketed separately)
- Fixes some typos and random upstyling
- Updates Turf from 1.4.0 to 2.0.2 in examples
- Fixes a typo in an example URL and redirects from old to new

/cc @jfirebaugh @tmcw

### CODE REVIEW

**Comment by jfirebaugh** [comment]
Looks great!

**Comment by geografa** [comment]
:+1:

**Comment by lyzidiamond** [comment]
@tmcw looks okay to merge here?

**Comment by lyzidiamond** [comment]
Merging!

**Pull request merged**
