### PR TITLE
New landing

### PR DESCRIPTION
**Pull request by tristen**
This commit creates more of brochure like layout for the front page. Here are notes from some of the commits:
- Skip redirect path to API
- Build out the overview page as a splash
- Build out map interactives on the landing to
  illustrate higher level ideas to build wit MapBox
- Start putting overview groups into call out sections and
  make copy edits
- Piece out sections that are more appropriate to the API docs from the landing.
- Methodize the site.defaultID string replacing
- Formatting, general copy editing
- Vertical spacing to address #542

### CODE REVIEW

**Comment by tmcw** [comment]
Pics plz

**Comment by tristen** [comment]
The API page is obviously unwieldly. [Here's a link to it](https://f.cloud.github.com/assets/61150/1563711/fec6bd6a-5064-11e3-8737-58e9ab03a5a4.png)

mapbox js - mapbox

**Comment by mourner** [comment]
:+1:

**Comment by heyitsgarrett** [comment]
:heart_eyes:

**Comment by tmcw** [comment]
:+1: :shipit:

**Comment by geografa** [comment]
nice!

**Comment by gundersen** [comment]
@tristen this new MapBox.js page looks amazing.

**Pull request merged**
