### PR TITLE
Add standalone mapbox.js info and change map id 

### PR DESCRIPTION
**Pull request by lyzidiamond**
This PR:
- Adds a box to the /mapbox.js page with info on mapbox.standalone.js, which is referred to in [our FAQ](https://www.mapbox.com/help/mapboxjs-a-leaflet-plugin/). Will change the language for that in the website repo.
- Removes the `examples` mapid from the /mapbox.js page and replaces it with `mapbox.streets`.

/cc @tmcw

### CODE REVIEW

**Comment by jfirebaugh** [comment]
I think this is better done as a subsection in [the "Guides" section of API.md](https://github.com/mapbox/mapbox.js/blob/mb-pages/API.md#guides). From there, it will automatically be pulled into the online docs at a URL like https://www.mapbox.com/mapbox.js/api/v2.1.7/standalone/, which you can link to from https://www.mapbox.com/help/mapboxjs-a-leaflet-plugin/ rather than saying "go to page A, click B, then look for C".

**Comment by lyzidiamond** [comment]
:+1: totally agree @jfirebaugh, will make that change

**Comment by lyzidiamond** [comment]
Thanks for the advice @jfirebaugh! This is now updated.

**Comment by jfirebaugh** [comment]
Should have noted this earlier, but I just remembered: we've deprecated mapbox.standalone.css, because it implies that you also need to supply leaflet.css, and that doesn't actually work. The correct usage is is leaflet.js + mapbox.standalone.js + mapbox.css. See https://github.com/mapbox/mapbox.js/issues/955 for more.

**Comment by lyzidiamond** [comment]
Updated the docs here.

**Pull request merged**
