### PR TITLE
Return the UI elements to the WMS example

### PR DESCRIPTION
**Pull request by wboykinm**
Re-added the layer switcher.

### CODE REVIEW

**Comment by wboykinm** [comment]
Holy hell. What's the Travis CI build about? :-1:

**Comment by jfirebaugh** [comment]
Yeah, Travis shouldn't be trying to build the gh-pages branch. I'll see if I can disable that.

**Comment by jfirebaugh** [comment]
travis-ci/travis-ci#1056

**Comment by jfirebaugh** [comment]
Hi @wboykinm, thanks for this.

When I try it out I see an error in the console: Uncaught TypeError: Cannot set property 'onclick' of null. Mind taking a look?

**Comment by jfirebaugh** [comment]
Oh, I see what's wrong. Happens in the current version too, will fix + merge.

**Pull request merged**
