### PR TITLE
Use innerHTML instead of innerText

### PR DESCRIPTION
**Pull request by tristen**
Address' https://github.com/mapbox/mapbox.js/issues/851

### CODE REVIEW

**Comment by tmcw** [comment]
Hm. Let's fallback to `.textContent` instead: using innerHTML will change behavior here and make this a potential security hole.

**Comment by jfirebaugh** [comment]
Pretty sure we should just use `textContent` unconditionally. `innerText` was my bad.

**Comment by tmcw** [comment]
innerText would give us IE8 support here - seems like it's worth it. IE8+ is still the advertised compatibility range.

**Comment by jfirebaugh** [comment]
Oh, I missed that. :+1:, carry on.

**Comment by jfirebaugh** [comment]
Hmm, diff now looks wrong though. `grid_control.js`?

**Pull request closed without merging**
