### PR TITLE
Support module exports for JSPM

### PR DESCRIPTION
**Pull request by lostinplace**
this is a simple, slightly hacky solution, that makes JSPM support immediately available

### CODE REVIEW

**Comment by lostinplace** [comment]
this reference #1003

**Comment by tmcw** [comment]
This is very hacky. Why does JSPM want this to be run in a function?

**Comment by lostinplace** [comment]
jshint warned about not using ""use strict"  so I added a strict function to manage the initializers.

This has nothing to do with jspm  It's worth noting that this will also fix the browserify problem

**Comment by tmcw** [comment]
Superseded by #1008

**Pull request closed without merging**
