### PR TITLE
Re theme

### PR DESCRIPTION
**Pull request by tristen**
This commit includes a re-working of the css and share control 
- [x] Controls look blank/broken on Retina
- [x] Test in :white_check_mark: ~~IE8~~, :white_check_mark: ~~IE9~~, :white_check_mark: ~~IE10~~
- [x] If there's a new build process and requirements for generating icons, it needs to be documented and explained for people new to the project.
#### CSS
- Consistify colors
- Use the border-box model throughout
- Consistify Leaflet controls and ui
- Sprite icons #364 
- Contain font sizes to the highest level and avoid defining specific cases so they may be overridden more easily 
- Removed the IE stylesheet. Fix up cases where this was needed or write in the changes to a browser section at the bottom of the stylesheet.
- Remove duplicate max-width #501
#### Share Control
- Add a pinterest share button
- Rewrite how the share modal is added to the page
- Fix up the event binding #514

### CODE REVIEW

**Comment by tmcw** [comment]
Added TODOs, otherwise looks great.

**Comment by tmcw** [comment]
Okay, made a tweak to connect Makefile dots. Remaining issue: I have inkscape installed, but don't have the `inkscape` binary: what magic is required to make that happen on OSX?

**Comment by tristen** [comment]
Should be `brew install inkscape`

**Comment by tmcw** [comment]
Okay, `brew install inkscape` fails for me currently but shouldn't be a blocker. Let's queue this up, work on the blog post, and sync it with Leaflet.

**Pull request merged**
